export class CustomerApplicationDTO
{
    email:string
    aadhar:string
    aadharno:string;
    agreement:string;
    appToe:string;
    empName:string;
    dob:Date
    gender:string;
    loa:string;
    estAmt:number;
    nationality:string;
    noc:string;
    org:string;
    pan:string;
    panno:string;
    proLoc:string;
    proName:string;
    retirAge:number;
    salary:number;
    salarySlp:string;
    voter:string;
    loanAmt:number;
    roi:number;
    tenure:number;
    status:string;
}